---
title: "Untitled"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

Column {data-width=650}
-----------------------------------------------------------------------
rm(list=ls()) 
library(tidyverse)
library(readr)
library(dplyr)

file_path <- "C:/Users/eskil/Downloads/df.csv"

# read the CSV file into a data frame
df <- read.csv(file_path)

### Chart A


```
library(magrittr)

total_sales_by_week <- aggregate(df$MOVE_SUM, by=list(df$WEEK), sum)




# print the total sales by week
print(total_sales_by_week)

ggplot(data=total_sales_by_week, aes(x=`Group.1`, y=x)) +
  geom_line(color="steelblue", size=1.1) +
  geom_smooth(method="auto", color="red") +
  labs(title="Total Sales by Week", x="Week", y="Total Sales")
Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
df_first_4_weeks <- subset(df, WEEK <= 4)


brand_sales <- aggregate(SUM_SALES ~ BRAND, data = df_first_4_weeks, sum)


total_sales <- sum(df_first_4_weeks$SUM_SALES)


brand_sales$SHARE <- brand_sales$SUM_SALES / total_sales
total_sales_by_brand <- aggregate(df$MOVE_SUM, by=list(df$BRAND), sum)

total_sales_by_brand$Market_Share <- total_sales_by_brand$x / sum(total_sales_by_brand$x) * 100


ggplot(total_sales_by_brand, aes(x="", y=x, fill=`Group.1`)) +
  geom_bar(stat="identity", width=1, color="black") +
  coord_polar(theta="y") +
  scale_fill_manual(values=c("#FFB6C1", "#66CDAA", "#56B4E9")) +
  labs(title="Market Share by Brand", fill="Brand") +
  geom_text(aes(label = paste0(round(Market_Share, 1), "%")), position=position_stack(vjust=0.5)) +
  theme_void()
```

### Chart C

```{r}

```

